public class Exceptions1 
{ 
    public static void main(String[] args) 
    { 
        int a = 5; 
        int b = 0; 
        int c = a/b; 
        System.out.println(c); } 
    }

=========================================
public class Exceptions2 
{ 
	public static void main(String[] args) 
	{ 
		try 
		{ 
			int a = 5; 
			int b = 0; 
			int c = a/b; 
			System.out.println(c); 
		} 
		catch (ArithmeticException e) 
		{ 
			System.out.println(e); 
			System.out.println("Oopss, there is an error!:("); 
		} 
	} 
}
================================
public class Exceptions3
{ 
	public static void main(String[] args) 
	{ 
		try 
		{ 
			int[] arr = new int[10]; 
			arr[12] = 15; 
			int a = 5; 
			int b = 0; 
			int c = a/b; 
			System.out.println(c); 
		} 
		catch (ArithmeticException e) 
		{ 
			System.out.println(e); 
			System.out.println("Oopss, there is an arithmetic exception error!:("); 
		} 
		catch (ArrayIndexOutOfBoundsException e) 
		{ 
			System.out.println(e); 
			System.out.println("Oopss, there is an array out of bound exception error!:("); 
		} 
	} 
}

=======================================
public class Exceptions4
{ 
	public static void main(String[] args) 
	{ 
		try 
		{ 
			int[] arr = new int[10]; 
			arr[12] = 15; 
		} 
		catch (ArrayIndexOutOfBoundsException e) 
		{ 
			System.out.println(e); 
			System.out.println("Oopss, there is an array out of bound exception error!:("); 
		} 
		try 
		{ 
			int a = 5; 
			int b = 0; 
			int c = a/b; 
			System.out.println(c); 
		} 
		catch (ArithmeticException e) 
		{ 
			System.out.println(e); 
			System.out.println("Oopss, there is an arithmetic exception error!:("); 
		} 
	} 
}


=============================================
public class Exceptions5 
{ 
	public static void main(String[] args) 
	{ 
	try 
	{ 	
		int[] arr = new int[10];
		arr[12] = 15; 
	} 
	catch (ArrayIndexOutOfBoundsException e) 
	{ 
		System.out.println(e);
		System.out.println("Oopss, there is an array out of bound exception error!:("); 
	} 
	try 
	{ 
		int a = 5; 
		int b = 0; 
		int c = a/b; 
		System.out.println(c); 
	} 
	catch (ArithmeticException e) 
	{ 
		System.out.println(); 
		System.out.println(e); 
		System.out.println("Oopss, there is an arithmetic exception error!:("); 
	} 
	finally 
	{ 
		System.out.println(); 
		System.out.println("Hehehe, I'm executed without any error!:)");
	} 
} 
}
============================================
import java.util.Scanner; 
public class Exceptions6 
{ 
	public static void main(String[] args) 
	{ 
		validate(); 
		System.out.println("Kia ora mate, have a nice day!:)"); 
	} 
	public static void validate() 
	{
		Scanner sc = new Scanner(System.in); 
		System.out.println("Enter your age: "); 
		int age = sc.nextInt(); 
		if(age<18) 
		try 
		{ 	
			throw new ArithmeticException("You are not eligible to vote!"); 
		} 
		catch (ArithmeticException e) 
		{ 
			System.out.println(e); 
			System.out.println("Sorry, you're too young to vote!:("); 
		} 
	} 
}